version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - DOCKER_REGISTRY_URL=https://index.docker.io/v1/
    ports:
      - "8081:8081"
    platform: linux/amd64


